### ISSUE TITLE
Connecting Issue with Test-Net Pool

### ISSUE THREAD

**Issue by N8Thrasher** [BTHPOS/BTH#8]
Running Windows_x64_nheqminer-5c
![image](https://user-images.githubusercontent.com/24593637/48132295-2189e800-e2a4-11e8-9d9f-e21d88d4c3be.png)

**Comment by dondreytaylor** [comment]
Ah looks like the version of nheqminer that we had on our repo did not have the updated personalization string for Bithereum. Try running this version https://github.com/BTHPOS/nheqminer. You'll have to compile it for Windows at the moment. I'll work to get some builds up soon.

**Comment by N8Thrasher** [comment]
I'll wait for the complete build then. thanks
