### ISSUE TITLE
 Release for windows

### ISSUE THREAD

**Issue by Konstantin35** [BTHPOS/BTH#9]
How soon will testnet release for windows?

**Comment by dondreytaylor** [comment]
Windows release will be available later today. I'll respond with a link to the release here.

**Comment by sky61** [comment]
News about windows version ?

**Comment by dondreytaylor** [comment]
Windows builds are now available @sky61 @Konstantin35. 
https://github.com/BTHPOS/BTH/releases

Let me know if you experience any issues. We will be resetting testnet at some point between today and tomorrow. Syncing with mainnet will commence when our full nodes hit BTC block #500,000; so in the meantime, your full nodes will remain at BTC block #0 until the minimum chain work has been reached.
